#!/usr/bin/env python3

import sys



def readHScores():
    result = ["error"]
    with open('HiScores.txt', "r") as textFile:
        lines = [line.split() for line in textFile]
    return lines



termArguments = sys.argv
firstCall = False

if(len(termArguments) == 1):
    termArguments.append("")

while(termArguments[1] != "quit"):
    if(termArguments[1] == "2048"):
        print("\nLaunching game : 2048 \n")
        with open("terminal2048/game.py", "rb") as source_file:
            code = compile(source_file.read(), "terminal2048/game.py", "exec")
        exec(code)
    if(termArguments[1] == "OsXs"):
        print("\nLaunching game : OsXs \n")
        with open("terminalOsXs/game.py", "rb") as source_file:
            code = compile(source_file.read(), "terminalOsXs/game.py", "exec")
        exec(code)
    elif(termArguments[1] == "help"):
        print("\nUsage: ./termGame [argument]")
        print("Optional arguments:\n")
        print('%12s'%"2048" + "\t:\tLaunch 2048 game")
        print('%12s'%"OsXs" + "\t:\tLaunch Os & Xs game")
        print('%12s'%"scores" + "\t:\tShow high scores for all games")
        print('%12s'%"help" + "\t:\tList termGame commands")
        print('%12s'%"quit" + "\t:\tExit termGame launcher\n")
    elif(termArguments[1] == "scores"):
        print("\nFetching Hi Score Table...\n")
        scores = readHScores()
        print("\n***********************************")
        print("*           HI SCORES             *")
        print("***********************************")
        print("*        " + scores[0][0] + "   *	" + scores[0][1] + "     *")
        print("***********************************")
        print("*" + '%12s'%"" + "\t*\t" + '%11s'%"*")
        for i in range(len(scores))[1:]:
            line = "*" + '%12s'%scores[i][0] + "\t*\t" + scores[i][1]
            for i in range(10-len(scores[i][1])):
                line += " "
            line += "*"
            print(line)
        print("*" + '%12s'%"" + "\t*\t" + '%11s'%"*")
        print("***********************************\n")
    elif(termArguments[1] != ""):
        print("\nCommand not recognised\n")

    print("\n\nPlease enter a command")
    print("Use 'quit' to exit or 'help' for a list of games\n")
    termArguments[1] = input("~~~ ")
